on:
  pull_request:
  push:
    branches:
      - main

name: Check and Lint

jobs:
  Flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # 4.0
      - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 #2.16
      - name: Pub Get
        run: dart pub get --no-precompile
        working-directory: build_tool
      - name: Dart Format
        run: dart format . --output=none --set-exit-if-changed
        working-directory: build_tool
      - name: Analyze
        run: dart analyze
        working-directory: build_tool
      - name: Test
        run: flutter test
        working-directory: build_tool
