on:
  pull_request:
  push:
    branches:
      - main

name: Check and Lint

jobs:
  Flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - name: Pub Get
        run: dart pub get --no-precompile
        working-directory: build_tool
      - name: Dart Format
        run: dart format . --output=none --set-exit-if-changed
        working-directory: build_tool
      - name: Analyze
        run: dart analyze
        working-directory: build_tool
      - name: Test
        run: flutter test
        working-directory: build_tool
